
# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_park?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=America/Campo_Grande
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações de Hibernação (Opcional, se estiver usando JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Configuração do Springdoc OpenAPI
springdoc.api-docs.path=/docs-park.html
springdoc.swagger-ui.path=/docs-park
springdoc.packgesToScan=com.mballem.demoparkapi.web.controller

